package org.jackey.hilog.crmlistener.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jackey.hilog.crmlistener.model.Crmlistener;
import org.jackey.hilog.crmlistener.model.CrmlistenerCriteria;

public interface CrmlistenerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_crmlistener
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    int countByExample(CrmlistenerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_crmlistener
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    int deleteByExample(CrmlistenerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_crmlistener
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_crmlistener
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    int insert(Crmlistener record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_crmlistener
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    int insertSelective(Crmlistener record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_crmlistener
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    List<Crmlistener> selectByExample(CrmlistenerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_crmlistener
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    Crmlistener selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_crmlistener
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    int updateByExampleSelective(@Param("record") Crmlistener record, @Param("example") CrmlistenerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_crmlistener
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    int updateByExample(@Param("record") Crmlistener record, @Param("example") CrmlistenerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_crmlistener
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    int updateByPrimaryKeySelective(Crmlistener record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_crmlistener
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    int updateByPrimaryKey(Crmlistener record);
}