package org.jackey.hianaly.crmlistener.model;

import java.util.Date;

public class Crmlistener {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_crmlistener.id
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_crmlistener.ts
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    private Date ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_crmlistener.hs
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    private String hs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_crmlistener.incoming
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    private Integer incoming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_crmlistener.total
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_crmlistener.error
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    private Integer error;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_crmlistener.qSize
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    private Integer qsize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_crmlistener.id
     *
     * @return the value of h_crmlistener.id
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_crmlistener.id
     *
     * @param id the value for h_crmlistener.id
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_crmlistener.ts
     *
     * @return the value of h_crmlistener.ts
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_crmlistener.ts
     *
     * @param ts the value for h_crmlistener.ts
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_crmlistener.hs
     *
     * @return the value of h_crmlistener.hs
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    public String getHs() {
        return hs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_crmlistener.hs
     *
     * @param hs the value for h_crmlistener.hs
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    public void setHs(String hs) {
        this.hs = hs == null ? null : hs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_crmlistener.incoming
     *
     * @return the value of h_crmlistener.incoming
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    public Integer getIncoming() {
        return incoming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_crmlistener.incoming
     *
     * @param incoming the value for h_crmlistener.incoming
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    public void setIncoming(Integer incoming) {
        this.incoming = incoming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_crmlistener.total
     *
     * @return the value of h_crmlistener.total
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_crmlistener.total
     *
     * @param total the value for h_crmlistener.total
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_crmlistener.error
     *
     * @return the value of h_crmlistener.error
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    public Integer getError() {
        return error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_crmlistener.error
     *
     * @param error the value for h_crmlistener.error
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    public void setError(Integer error) {
        this.error = error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_crmlistener.qSize
     *
     * @return the value of h_crmlistener.qSize
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    public Integer getQsize() {
        return qsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_crmlistener.qSize
     *
     * @param qsize the value for h_crmlistener.qSize
     *
     * @mbggenerated Wed Aug 27 00:38:48 CST 2014
     */
    public void setQsize(Integer qsize) {
        this.qsize = qsize;
    }
}